jd:
  headers:
    referer: ""
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
  root_url: https://www.jd.com/
  clock_url: https://a.jd.com//ajax/queryServerData.html
  user_url_prefix: https://passport.jd.com/user/petName/getUserInfoForMiniJd.action?&callback=jsonpUserinfo&_=  # 用户信息获取地址
  buy_url: https://cart.jd.com/gate.action?pid={}&pcount=1&ptype=1 # 加购物车
  change_num: https://cart.jd.com/changeNum.action?pid={}&pcount=1&ptype=1 # 修改购物车商品数量为1
  pay_url: https://cart.jd.com/gotoOrder.action # 下单
  pay_success: https://trade.jd.com/shopping/order/submitOrder.action # 订单提交